case ":$PATH:" in
  *":$HOME/bin:"*) ;;
  *) export PATH="$HOME/bin:$PATH" ;;
esac

case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac

prompt_user=''
if [ "${EUID:-$(id -u)}" -eq 0 ]; then
  prompt_user='\[\e[33m\]\u@'
elif [ "${USER:-$(id -un)}" != "jodok" ] && [ "${USER:-$(id -un)}" != "admin" ]; then
  prompt_user='\[\e[33m\]\u@'
fi

PS1="${prompt_user}\[\e[31m\]\h\[\e[0m\] \[\e[1;32m\]➜\[\e[0m\] \[\e[36m\]\w\[\e[0m\] "

alias oh-my-jodok='$HOME/.jodok/update.sh'

[ -f "$HOME/.bashrc.local" ] && source "$HOME/.bashrc.local"
